import 'workout_plan.dart';

List<WorkoutPlan> getTrainingPlans() {
  return [
    WorkoutPlan(
      level: "Beginner",
      description: "This is a beginner-level training plan designed for new athletes.",
      infoText: "This 20-30 minute plan is tailored for football players and requires no equipment. It focuses on building strength, stability, and flexibility to help prevent ACL injuries. Featuring dynamic warm-ups, core stabilization, and plyometric exercises, it enhances balance, coordination, and injury resilience. Perfect for starting your journey to safer and stronger performance!",
      exercises: [
        Exercise(
          name: "High Knees (Skip A)",
          description: "High, dynamic knee lifts at a fast pace with intense arm movement.",
          purpose: "Activates hip and knee muscles, improves coordination.",
          imagePath: "assets/images/1.1.jpg",
          repetitions: "",
          sets: 1,
          isTimed: true,
          duration: 60,
        ),
        Exercise(
          name: "Butt Kicks (Skip C)",
          description: "Dynamic knee flexion with heels touching the glutes.",
          purpose: "Warms up the hamstrings.",
          imagePath: "assets/images/1.2.jpg",
         repetitions: "",
          sets: 1,
          isTimed: true,
          duration: 60,
        ),
        Exercise(
          name: "Leg Swings (Front-Back)",
          description: "Standing on one leg, perform controlled swings with the other leg forward and backward.",
          purpose: "Warms up hips and improves range of motion.",
          imagePath: "assets/images/1.3.png",
          repetitions: "10 on each leg",
          sets: 1,
          isTimed: false,
        ),
        Exercise(
          name: "Jumping Jacks",
          description: "Standard jumping jacks with dynamic arm and leg movements.",
          purpose: "Increases heart rate, prepares the whole body for exercise.",
          imagePath: "assets/images/1.4.png",
          repetitions: "",
          sets: 1,
          isTimed: true,
          duration: 120,
        ),
        Exercise(
          name: "Dynamic Squats (Air Squats)",
          description: "Squat to a 90° angle and return to a standing position with dynamic arm extension overhead.",
          purpose: "Activates quadriceps and glutes.",
          imagePath: "assets/images/1.5.png",
          repetitions: "10",
          sets: 1,
        ),
        Exercise(
          name: "Plank",
          description: "Maintain a forearm plank position with the body in a straight line.",
          purpose: "Strengthens core muscles, stabilizes the torso.",
          imagePath: "assets/images/1.6.png",
          repetitions: "",
          sets: 2,
          isTimed: true,
          duration: 30,
        ),

        Exercise(
            name: "Side Plank",
            description: "Maintain a side plank position on one forearm, keeping the hips aligned.",
            purpose: "Strengthens oblique muscles, improves lateral stability.",
            imagePath: "assets/images/1.7.png",
            repetitions: "",
            sets: 2,
            isTimed: true,
            duration: 20,
        ),

        Exercise(
            name: "Squats with Heel Raises",
            description: "Perform a 90° squat, then rise onto your toes.",
            purpose: "Strengthens thighs and calves, improves knee stability.",
            imagePath: "assets/images/1.8.png",
            repetitions: "10",
            sets: 3,
        ),

        Exercise(
            name: "Glute Bridge",
            description: "Lie on your back, bend your knees, lift your hips, hold for 2 seconds, and return to the starting position.",
            purpose: "Strengthens glutes and hamstrings.",
            imagePath: "assets/images/1.9.png",
            repetitions: "12",
            sets: 2,
        ),

        Exercise(
            name: "Vertical Jumps",
            description: "From a half-squat position, jump vertically and land softly on your toes.",
            purpose: "Improves explosive power and landing technique.",
            imagePath: "assets/images/1.10.png",
            repetitions: "8",
            sets: 3,
        ),

        Exercise(
             name: "Single-Leg Deadlift",
              description: "Stand on one leg, hinge at the hips, and lower your torso forward while extending the other leg backward. Return to the starting position.",
              purpose: "Strengthens hamstrings, glutes, and improves balance.",
              imagePath: "assets/images/1.11.png",
              repetitions: "10 per leg",
              sets: 2,
        ),

        Exercise(
            name: "Mountain Climbers",
            description: "In a plank position, alternately bring knees toward the chest at a fast pace.",
            purpose: "Engages core muscles, improves dynamic stability.",
            imagePath: "assets/images/1.12.png",
            repetitions: "",
            sets: 2,
            isTimed: true,
            duration: 30,
        ),

        Exercise(
            name: "Forward Fold",
            description: "From a standing position, bend forward and try to touch the floor.",
            purpose: "Stretches hamstrings and lower back.",
            imagePath: "assets/images/1.13.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
        ),

        Exercise(
            name: "Quadriceps Stretch",
            description: "Standing on one leg, pull the opposite foot toward your glutes.",
            purpose: "Stretches the quadriceps.",
            imagePath: "assets/images/1.14.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
        ),

        Exercise(
            name: "Hip and Glute Stretch",
            description: "Sit in a 'pigeon' pose with one leg bent in front and the other extended backward.",
            purpose: "Stretches hips and glutes.",
            imagePath: "assets/images/1.15.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
        ),

        Exercise(
            name: "Chest and Arm Stretch",
            description: "Interlace your fingers behind your back and lift your arms upward.",
            purpose: "Stretches chest and arms.",
            imagePath: "assets/images/1.16.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
        ),

      ],
    ),
  WorkoutPlan(
        level: "Intermediate",
        description: "This is an intermediate-level training plan designed for athletes looking to improve strength, stability, and performance.",
        infoText: "This 30-40 minute plan incorporates resistance bands and advanced dynamic exercises. It is tailored for soccer players to enhance strength, balance, and coordination, focusing on reducing the risk of ACL injuries. Featuring resistance training, single-leg stability work, and dynamic core movements, this plan prepares you for the next level of athletic performance.",
        exercises: [
          // Warm-Up
          Exercise(
            name: "High Knees (Skip A)",
            description: "Stand tall, drive your knees up toward your chest, and pump your arms alternately at a fast pace. Keep your core engaged.",
            purpose: "Activates hip and knee muscles, improves coordination.",
            imagePath: "assets/images/1.1.jpg",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 60,
          ),
          Exercise(
            name: "Butt Kicks (Skip C)",
            description: "Jog in place while kicking your heels up toward your glutes with each step. Keep your core tight and posture upright.",
            purpose: "Warms up the hamstrings.",
            imagePath: "assets/images/1.2.jpg",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 60,
          ),
          Exercise(
            name: "Lateral Band Walks",
            description: "Place a resistance band above your knees. With knees slightly bent, step laterally to one side while keeping band tension. Step back in the other direction.",
            purpose: "Strengthens glutes and improves knee stability.",
            imagePath: "assets/images/2.0.png",
            repetitions: "10 steps each direction",
            sets: 2,
          ),

          // Main Workout (Strength and Stability)
          Exercise(
            name: "Bodyweight Split Squats",
            description: "Stand with one foot forward and the other behind. Lower your back knee toward the floor while keeping your chest upright. Push back to the starting position.",
            purpose: "Builds single-leg strength, balance, and knee control.",
            imagePath: "assets/images/2.1.png",
            repetitions: "8 per leg",
            sets: 2,
          ),
          Exercise(
            name: "Banded Squats with Leg Abduction",
            description: "Place a resistance band above your knees. Squat down, and as you stand, lift one leg outward to the side. Alternate legs.",
            purpose: "Strengthens glutes, abductors, and thighs dynamically.",
            imagePath: "assets/images/2.2.png",
            repetitions: "10-12",
            sets: 3,
          ),
          Exercise(
            name: "Single-Leg Deadlift with Resistance Band",
            description: "Anchor a resistance band under one foot and hold the band with both hands. Hinge forward at the hips, extending the opposite leg back, then return to standing.",
            purpose: "Strengthens the hamstrings, glutes, and improves balance.",
            imagePath: "assets/images/2.3.png",
            repetitions: "8-10 per leg",
            sets: 2,
          ),
          Exercise(
            name: "Glute Bridge with Resistance Band",
            description: "Lie on your back with knees bent and a resistance band above your knees. Push through your heels to lift your hips. Hold briefly at the top, then lower back down.",
            purpose: "Strengthens glutes and stabilizes the pelvis.",
            imagePath: "assets/images/2.5.png",
            repetitions: "12",
            sets: 3,
          ),
          Exercise(
            name: "Resistance Band Clamshells",
            description: "Lie on your side with a resistance band above your knees. Keep feet together and lift the top knee while keeping hips stable. Lower back down.",
            purpose: "Improves hip stability and knee alignment.",
            imagePath: "assets/images/2.7.png",
            repetitions: "12 per side",
            sets: 2,
          ),
          Exercise(
            name: "Jump Squats with Band",
            description: "Place a resistance band above your knees. Perform a squat, then jump explosively, landing softly with control.",
            purpose: "Develops power and reinforces safe landing mechanics.",
            imagePath: "assets/images/2.8.png",
            repetitions: "8-10",
            sets: 2,
          ),
          Exercise(
            name: "Mountain Climbers with Band",
            description: "Start in a plank position with a resistance band around your feet. Drive your knees alternately toward your chest while maintaining tension.",
            purpose: "Strengthens core and hip flexors.",
            imagePath: "assets/images/1.12.png",
            repetitions: "",
            sets: 2,
            isTimed: true,
            duration: 30,
          ),
          Exercise(
            name: "Spiderman Plank",
            description: "Start in a plank position with hands under shoulders. Bring one knee toward the outside of your elbow, alternating sides.",
            purpose: "Engages the core and improves hip and knee mobility.",
            imagePath: "assets/images/2.4.png",
            repetitions: "10 per side",
            sets: 2,
          ),

          // Cool-Down
          Exercise(
            name: "Standing Hamstring Stretch",
            description: "Stand tall and place one foot forward with your heel on the ground. Lean forward from your hips to feel a stretch in the back of your thigh.",
            purpose: "Relaxes hamstrings and improves flexibility.",
            imagePath: "assets/images/2.9.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
          ),
          Exercise(
            name: "Quadriceps Stretch",
            description: "Stand on one leg and pull the opposite foot toward your glutes. Hold onto a stable surface for balance if needed.",
            purpose: "Stretches the quadriceps.",
            imagePath: "assets/images/1.14.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
          ),
          Exercise(
            name: "Hip Flexor Stretch",
            description: "Kneel on one knee with the other foot forward. Push your hips gently forward to feel a stretch in the front of the hip.",
            purpose: "Improves flexibility in hip flexors.",
            imagePath: "assets/images/2.10.png",
            repetitions: "",
            sets: 1,
            isTimed: true,
            duration: 20,
          ),
        ],
      ),

  ];
}
